### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by scally** [jannishuebl/electron_opal#1]
This seems promising; is there any sample/example app that demonstrates how to use the wrapper? 😄

**Comment by illtellyoulater** [comment]
:+1:

**Comment by sam0x17** [comment]
An example app has been posted in @youchan's fork https://github.com/youchan/electron_opal

**Comment by jannishuebl** [comment]
Sorry Guys for not answering, I do not use the project anymore and will not maintain.

**Comment by illtellyoulater** [comment]
@scally I think Flammarion at https://github.com/zach-capalbo/flammarion is a similar and more recent project, but do not forget to check out the new Ruby2D gem (www.ruby2d.com - https://github.com/ruby2d/ruby2d) which supports both native graphics rendering (it will compile down to a native executable and it's x-platform) or browser rendering (I am not sure whether it also uses Opal or not). I hope it helps!
